---
apiVersion: v1
kind: Namespace
metadata: 
  name: codeserver
  labels:
    app: cs
    name: codeserver
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-cm
  namespace: codeserver
  labels:
    app: cs
    name: cs-cm
data:
  TZ: /Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-157.230.196.33.nip.io