---
apiVersion: v1
kind: Secret
metadata:
  name: cs-secret
  namespace: codeserver
  labels:
    app: cs
    name: cs-secret
type: Opaque
data:
  PASSWORD: Y29kZXNlcnZlcnBhc3M=
  SUDO_PASSWORD: Y29kZXNlcnZlcnBhc3M=
